services:
  mysql:
    container_name: mySql-OneBox-db
    image: 'mysql:latest'
    restart: on-failure
    volumes:
      - onebox-volume:/var/lib/app/mysql/data
    env_file:
      - mysql-db.dev.env
    ports:
      - '3306'

volumes:
  onebox-volume: